//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.TaskPlan {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtTaskID;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorID;
		protected global::System.Web.UI.WebControls.TextBox txtTaskName;
		protected global::System.Web.UI.WebControls.TextBox txtCommandID;
		protected global::System.Web.UI.WebControls.TextBox txtCommandInfo;
		protected global::System.Web.UI.WebControls.TextBox txtMeterAddr;
		protected global::System.Web.UI.WebControls.TextBox txtMeterType;
		protected global::System.Web.UI.WebControls.TextBox txtMeterItem;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeDate;
		protected global::System.Web.UI.WebControls.TextBox txtTaskMonth;
		protected global::System.Web.UI.WebControls.TextBox txtTaskDay;
		protected global::System.Web.UI.WebControls.TextBox txtTaskHour;
		protected global::System.Web.UI.WebControls.TextBox txtTaskMinute;
		protected global::System.Web.UI.WebControls.TextBox txtExeMark;
		protected global::System.Web.UI.WebControls.TextBox txtExeDate;
		protected global::System.Web.UI.WebControls.TextBox txtExeError;
		protected global::System.Web.UI.WebControls.TextBox txtTaskMark;
		protected global::System.Web.UI.WebControls.TextBox txtTaskType;
		protected global::System.Web.UI.WebControls.TextBox txtTaskError;
		protected global::System.Web.UI.WebControls.TextBox txtTryNum;
		protected global::System.Web.UI.WebControls.TextBox txtHostAddr;
		protected global::System.Web.UI.WebControls.TextBox txtInsDate;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtTaskFrequency;
		protected global::System.Web.UI.WebControls.TextBox txtExeInfo;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtDeptID;
		protected global::System.Web.UI.WebControls.TextBox txtTaskWeek;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtServerId;
		protected global::System.Web.UI.WebControls.TextBox txtExeType;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
