//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.TaskPlan {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblTaskID;
	protected global::System.Web.UI.WebControls.Label lblCollectorID;
	protected global::System.Web.UI.WebControls.Label lblTaskName;
	protected global::System.Web.UI.WebControls.Label lblCommandID;
	protected global::System.Web.UI.WebControls.Label lblCommandInfo;
	protected global::System.Web.UI.WebControls.Label lblMeterAddr;
	protected global::System.Web.UI.WebControls.Label lblMeterType;
	protected global::System.Web.UI.WebControls.Label lblMeterItem;
	protected global::System.Web.UI.WebControls.Label lblFreezeDate;
	protected global::System.Web.UI.WebControls.Label lblTaskMonth;
	protected global::System.Web.UI.WebControls.Label lblTaskDay;
	protected global::System.Web.UI.WebControls.Label lblTaskHour;
	protected global::System.Web.UI.WebControls.Label lblTaskMinute;
	protected global::System.Web.UI.WebControls.Label lblExeMark;
	protected global::System.Web.UI.WebControls.Label lblExeDate;
	protected global::System.Web.UI.WebControls.Label lblExeError;
	protected global::System.Web.UI.WebControls.Label lblTaskMark;
	protected global::System.Web.UI.WebControls.Label lblTaskType;
	protected global::System.Web.UI.WebControls.Label lblTaskError;
	protected global::System.Web.UI.WebControls.Label lblTryNum;
	protected global::System.Web.UI.WebControls.Label lblHostAddr;
	protected global::System.Web.UI.WebControls.Label lblInsDate;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblTaskFrequency;
	protected global::System.Web.UI.WebControls.Label lblExeInfo;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblDeptID;
	protected global::System.Web.UI.WebControls.Label lblTaskWeek;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID;
	protected global::System.Web.UI.WebControls.Label lblServerId;
	protected global::System.Web.UI.WebControls.Label lblExeType;


       
    }
}
