//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ClientEnvironmentInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDanWeiName;
	protected global::System.Web.UI.WebControls.Label lblJiQiMa;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorCode;
		protected global::System.Web.UI.WebControls.TextBox txtIP;
		protected global::System.Web.UI.WebControls.TextBox txtBrowserName;
		protected global::System.Web.UI.WebControls.TextBox txtBrowerVersion;
		protected global::System.Web.UI.WebControls.TextBox txtOSName;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
