//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ClientEnvironmentInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDanWeiName;
	protected global::System.Web.UI.WebControls.Label lblJiQiMa;
	protected global::System.Web.UI.WebControls.Label lblOperatorCode;
	protected global::System.Web.UI.WebControls.Label lblIP;
	protected global::System.Web.UI.WebControls.Label lblBrowserName;
	protected global::System.Web.UI.WebControls.Label lblBrowerVersion;
	protected global::System.Web.UI.WebControls.Label lblOSName;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;


       
    }
}
