//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PreOperationFare {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtOperID;
		protected global::System.Web.UI.WebControls.TextBox txtFareID;
		protected global::System.Web.UI.WebControls.TextBox txtFareTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtFarePrice;
		protected global::System.Web.UI.WebControls.TextBox txtFareMoney;
		protected global::System.Web.UI.WebControls.TextBox txtFareMoney1;
		protected global::System.Web.UI.WebControls.TextBox txtFarePrice2;
		protected global::System.Web.UI.WebControls.TextBox txtFareMoney2;
		protected global::System.Web.UI.WebControls.TextBox txtFarePrice3;
		protected global::System.Web.UI.WebControls.TextBox txtFareMoney3;
		protected global::System.Web.UI.WebControls.TextBox txtTaxRate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
