//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Operators {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorCode;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorName;
		protected global::System.Web.UI.WebControls.TextBox txtRoleID;
		protected global::System.Web.UI.WebControls.TextBox txtOperPassword;
		protected global::System.Web.UI.WebControls.TextBox txtSiteID;
		protected global::System.Web.UI.WebControls.TextBox txtFlag;
		protected global::System.Web.UI.WebControls.TextBox txtCreateDate;
		protected global::System.Web.UI.WebControls.TextBox txtLastLoginDate;
		protected global::System.Web.UI.WebControls.TextBox txtPageRowCounts;
		protected global::System.Web.UI.WebControls.TextBox txtOperLevel;
		protected global::System.Web.UI.WebControls.TextBox txtTemplateID;
		protected global::System.Web.UI.WebControls.TextBox txtPaymentTemplateID;
		protected global::System.Web.UI.WebControls.TextBox txtICTemplateID;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtSelfSetting;
		protected global::System.Web.UI.WebControls.TextBox txtAutoRead;
		protected global::System.Web.UI.WebControls.TextBox txtPhoneSerialNumber;
		protected global::System.Web.UI.WebControls.TextBox txtIsBinding;
		protected global::System.Web.UI.WebControls.TextBox txtRoleLevel;
		protected global::System.Web.UI.WebControls.TextBox txtExpiryDate;
		protected global::System.Web.UI.WebControls.TextBox txtSkin;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
