//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Operators {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblOperatorCode;
	protected global::System.Web.UI.WebControls.Label lblOperatorName;
	protected global::System.Web.UI.WebControls.Label lblRoleID;
	protected global::System.Web.UI.WebControls.Label lblOperPassword;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblCreateDate;
	protected global::System.Web.UI.WebControls.Label lblLastLoginDate;
	protected global::System.Web.UI.WebControls.Label lblPageRowCounts;
	protected global::System.Web.UI.WebControls.Label lblOperLevel;
	protected global::System.Web.UI.WebControls.Label lblTemplateID;
	protected global::System.Web.UI.WebControls.Label lblPaymentTemplateID;
	protected global::System.Web.UI.WebControls.Label lblICTemplateID;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblSelfSetting;
	protected global::System.Web.UI.WebControls.Label lblAutoRead;
	protected global::System.Web.UI.WebControls.Label lblPhoneSerialNumber;
	protected global::System.Web.UI.WebControls.Label lblIsBinding;
	protected global::System.Web.UI.WebControls.Label lblRoleLevel;
	protected global::System.Web.UI.WebControls.Label lblExpiryDate;
	protected global::System.Web.UI.WebControls.Label lblSkin;


       
    }
}
