//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MetersDev {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtDisenableDate;
		protected global::System.Web.UI.WebControls.TextBox txtSiteDir;
		protected global::System.Web.UI.WebControls.TextBox txtInsureCode;
		protected global::System.Web.UI.WebControls.TextBox txtInsureDate;
		protected global::System.Web.UI.WebControls.TextBox txtInsureEndDate;
		protected global::System.Web.UI.WebControls.TextBox txtGasDir;
		protected global::System.Web.UI.WebControls.TextBox txtInstallPos;
		protected global::System.Web.UI.WebControls.TextBox txtInstallWorkerID;
		protected global::System.Web.UI.WebControls.TextBox txtInstallDate;
		protected global::System.Web.UI.WebControls.TextBox txtFireWorkerID;
		protected global::System.Web.UI.WebControls.TextBox txtFireDate;
		protected global::System.Web.UI.WebControls.TextBox txtFirstCheckDate;
		protected global::System.Web.UI.WebControls.TextBox txtFirstCheckMark;
		protected global::System.Web.UI.WebControls.TextBox txtCheckCyc;
		protected global::System.Web.UI.WebControls.TextBox txtBoilerFlag;
		protected global::System.Web.UI.WebControls.TextBox txtSelfFlag;
		protected global::System.Web.UI.WebControls.TextBox txtBookID;
		protected global::System.Web.UI.WebControls.TextBox txtInstallID;
		protected global::System.Web.UI.WebControls.TextBox txtFirstCheckInfo;
		protected global::System.Web.UI.WebControls.TextBox txtFirstCheckWorkerID;
		protected global::System.Web.UI.WebControls.TextBox txtCurrValveState;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
