//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MetersDev {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblDisenableDate;
	protected global::System.Web.UI.WebControls.Label lblSiteDir;
	protected global::System.Web.UI.WebControls.Label lblInsureCode;
	protected global::System.Web.UI.WebControls.Label lblInsureDate;
	protected global::System.Web.UI.WebControls.Label lblInsureEndDate;
	protected global::System.Web.UI.WebControls.Label lblGasDir;
	protected global::System.Web.UI.WebControls.Label lblInstallPos;
	protected global::System.Web.UI.WebControls.Label lblInstallWorkerID;
	protected global::System.Web.UI.WebControls.Label lblInstallDate;
	protected global::System.Web.UI.WebControls.Label lblFireWorkerID;
	protected global::System.Web.UI.WebControls.Label lblFireDate;
	protected global::System.Web.UI.WebControls.Label lblFirstCheckDate;
	protected global::System.Web.UI.WebControls.Label lblFirstCheckMark;
	protected global::System.Web.UI.WebControls.Label lblCheckCyc;
	protected global::System.Web.UI.WebControls.Label lblBoilerFlag;
	protected global::System.Web.UI.WebControls.Label lblSelfFlag;
	protected global::System.Web.UI.WebControls.Label lblBookID;
	protected global::System.Web.UI.WebControls.Label lblInstallID;
	protected global::System.Web.UI.WebControls.Label lblFirstCheckInfo;
	protected global::System.Web.UI.WebControls.Label lblFirstCheckWorkerID;
	protected global::System.Web.UI.WebControls.Label lblCurrValveState;


       
    }
}
