//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterImageParam {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblMeterId;
	protected global::System.Web.UI.WebControls.Label lblCameraNo;
		protected global::System.Web.UI.WebControls.TextBox txtNumberCount;
		protected global::System.Web.UI.WebControls.TextBox txtCaptureStartPixs;
		protected global::System.Web.UI.WebControls.TextBox txtUpClipPixs;
		protected global::System.Web.UI.WebControls.TextBox txtDownClipPixs;
		protected global::System.Web.UI.WebControls.TextBox txtLeftClipPixs;
		protected global::System.Web.UI.WebControls.TextBox txtRightClipPixs;
		protected global::System.Web.UI.WebControls.TextBox txtCircumgyrateDegree;
		protected global::System.Web.UI.WebControls.TextBox txtInclineDegree;
		protected global::System.Web.UI.WebControls.TextBox txtModelHeight;
		protected global::System.Web.UI.WebControls.TextBox txtModelWidth;
		protected global::System.Web.UI.WebControls.TextBox txtModelOneWidth;
		protected global::System.Web.UI.WebControls.TextBox txtNumberSpace;
		protected global::System.Web.UI.WebControls.TextBox txtBitValueLimen;
		protected global::System.Web.UI.WebControls.TextBox txtBitValueRadius;
		protected global::System.Web.UI.WebControls.TextBox txtBitValueBlackProportion;
		protected global::System.Web.UI.WebControls.TextBox txtMorphologicFilterParam;
		protected global::System.Web.UI.WebControls.TextBox txtSearchlimitParam;
		protected global::System.Web.UI.WebControls.TextBox txtWindowHeight;
		protected global::System.Web.UI.WebControls.TextBox txtLastOperDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
