//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterImageParam {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblMeterId;
	protected global::System.Web.UI.WebControls.Label lblCameraNo;
	protected global::System.Web.UI.WebControls.Label lblNumberCount;
	protected global::System.Web.UI.WebControls.Label lblCaptureStartPixs;
	protected global::System.Web.UI.WebControls.Label lblUpClipPixs;
	protected global::System.Web.UI.WebControls.Label lblDownClipPixs;
	protected global::System.Web.UI.WebControls.Label lblLeftClipPixs;
	protected global::System.Web.UI.WebControls.Label lblRightClipPixs;
	protected global::System.Web.UI.WebControls.Label lblCircumgyrateDegree;
	protected global::System.Web.UI.WebControls.Label lblInclineDegree;
	protected global::System.Web.UI.WebControls.Label lblModelHeight;
	protected global::System.Web.UI.WebControls.Label lblModelWidth;
	protected global::System.Web.UI.WebControls.Label lblModelOneWidth;
	protected global::System.Web.UI.WebControls.Label lblNumberSpace;
	protected global::System.Web.UI.WebControls.Label lblBitValueLimen;
	protected global::System.Web.UI.WebControls.Label lblBitValueRadius;
	protected global::System.Web.UI.WebControls.Label lblBitValueBlackProportion;
	protected global::System.Web.UI.WebControls.Label lblMorphologicFilterParam;
	protected global::System.Web.UI.WebControls.Label lblSearchlimitParam;
	protected global::System.Web.UI.WebControls.Label lblWindowHeight;
	protected global::System.Web.UI.WebControls.Label lblLastOperDate;


       
    }
}
