//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterTransferOperation {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtOldUserID;
		protected global::System.Web.UI.WebControls.TextBox txtOldUserName;
		protected global::System.Web.UI.WebControls.TextBox txtOldUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtOldLastReadNumber;
		protected global::System.Web.UI.WebControls.TextBox txtOldUserReserve;
		protected global::System.Web.UI.WebControls.TextBox txtNewUserID;
		protected global::System.Web.UI.WebControls.TextBox txtNewUserName;
		protected global::System.Web.UI.WebControls.TextBox txtNewUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtBeginDate;
		protected global::System.Web.UI.WebControls.TextBox txtOperDateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
