//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterTransferOperation {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblOldUserID;
	protected global::System.Web.UI.WebControls.Label lblOldUserName;
	protected global::System.Web.UI.WebControls.Label lblOldUserCode;
	protected global::System.Web.UI.WebControls.Label lblOldLastReadNumber;
	protected global::System.Web.UI.WebControls.Label lblOldUserReserve;
	protected global::System.Web.UI.WebControls.Label lblNewUserID;
	protected global::System.Web.UI.WebControls.Label lblNewUserName;
	protected global::System.Web.UI.WebControls.Label lblNewUserCode;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblBeginDate;
	protected global::System.Web.UI.WebControls.Label lblOperDateTime;


       
    }
}
