//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FreezeMonthls {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeMonth;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeNumber;
		protected global::System.Web.UI.WebControls.TextBox txtReadDate;
		protected global::System.Web.UI.WebControls.CheckBox chkCalMark;
		protected global::System.Web.UI.WebControls.TextBox txtInstantNumber;
		protected global::System.Web.UI.WebControls.TextBox txtPileNumber;
		protected global::System.Web.UI.WebControls.TextBox txtWatertemp;
		protected global::System.Web.UI.WebControls.TextBox txtBackWatertemp;
		protected global::System.Web.UI.WebControls.TextBox txtWorkDate;
		protected global::System.Web.UI.WebControls.TextBox txtFactDate;
		protected global::System.Web.UI.WebControls.TextBox txtBatteryState;
		protected global::System.Web.UI.WebControls.TextBox txtWarning;
		protected global::System.Web.UI.WebControls.TextBox txtReadType;
		protected global::System.Web.UI.WebControls.TextBox txtOldFreezeNumber;
		protected global::System.Web.UI.WebControls.TextBox txtMegabit;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
