//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.EInvoices {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtOperID;
		protected global::System.Web.UI.WebControls.TextBox txtOperType;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceNumber;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNo;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtOperMoney;
		protected global::System.Web.UI.WebControls.TextBox txtFactMoney;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceState;
		protected global::System.Web.UI.WebControls.TextBox txtOperDate;
		protected global::System.Web.UI.WebControls.TextBox txtURL;
		protected global::System.Web.UI.WebControls.TextBox txtCreateDate;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceCode;
		protected global::System.Web.UI.WebControls.TextBox txtRtnInvoiceNumber;
		protected global::System.Web.UI.WebControls.TextBox txtManualRegist;
		protected global::System.Web.UI.WebControls.TextBox txtRedSaleURL;
		protected global::System.Web.UI.WebControls.TextBox txtRSInvoiceNumber;
		protected global::System.Web.UI.WebControls.TextBox txtRegistDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
