//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.EInvoices {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblOperID;
	protected global::System.Web.UI.WebControls.Label lblOperType;
	protected global::System.Web.UI.WebControls.Label lblInvoiceNumber;
	protected global::System.Web.UI.WebControls.Label lblOrderNo;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblOperMoney;
	protected global::System.Web.UI.WebControls.Label lblFactMoney;
	protected global::System.Web.UI.WebControls.Label lblInvoiceState;
	protected global::System.Web.UI.WebControls.Label lblOperDate;
	protected global::System.Web.UI.WebControls.Label lblURL;
	protected global::System.Web.UI.WebControls.Label lblCreateDate;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblInvoiceCode;
	protected global::System.Web.UI.WebControls.Label lblRtnInvoiceNumber;
	protected global::System.Web.UI.WebControls.Label lblManualRegist;
	protected global::System.Web.UI.WebControls.Label lblRedSaleURL;
	protected global::System.Web.UI.WebControls.Label lblRSInvoiceNumber;
	protected global::System.Web.UI.WebControls.Label lblRegistDate;


       
    }
}
