//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PriceFare {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtFareTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtPrice2;
		protected global::System.Web.UI.WebControls.TextBox txtPrice3;
		protected global::System.Web.UI.WebControls.TextBox txtFareNo;
		protected global::System.Web.UI.WebControls.TextBox txtReMark;
		protected global::System.Web.UI.WebControls.TextBox txtPrice4;
		protected global::System.Web.UI.WebControls.TextBox txtPrice5;
		protected global::System.Web.UI.WebControls.TextBox txtPrice6;
		protected global::System.Web.UI.WebControls.TextBox txtTaxRate;
		protected global::System.Web.UI.WebControls.TextBox txtProjectName;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
