//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PriceFare {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblFareID;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID;
	protected global::System.Web.UI.WebControls.Label lblFareTypeName;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblPrice2;
	protected global::System.Web.UI.WebControls.Label lblPrice3;
	protected global::System.Web.UI.WebControls.Label lblFareNo;
	protected global::System.Web.UI.WebControls.Label lblReMark;
	protected global::System.Web.UI.WebControls.Label lblPrice4;
	protected global::System.Web.UI.WebControls.Label lblPrice5;
	protected global::System.Web.UI.WebControls.Label lblPrice6;
	protected global::System.Web.UI.WebControls.Label lblTaxRate;
	protected global::System.Web.UI.WebControls.Label lblProjectName;


       
    }
}
