//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.TaskPlanLog {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtTaskID;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorID;
		protected global::System.Web.UI.WebControls.TextBox txtMeterAddr;
		protected global::System.Web.UI.WebControls.TextBox txtMeterType;
		protected global::System.Web.UI.WebControls.TextBox txtExeMark;
		protected global::System.Web.UI.WebControls.TextBox txtExeDate;
		protected global::System.Web.UI.WebControls.TextBox txtExeInfo;
		protected global::System.Web.UI.WebControls.TextBox txtInsDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
