//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.UserRegist {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtRegistPhone;
		protected global::System.Web.UI.WebControls.TextBox txtPassWord;
		protected global::System.Web.UI.WebControls.TextBox txtIdentityCard;
		protected global::System.Web.UI.WebControls.TextBox txtFlag;
		protected global::System.Web.UI.WebControls.TextBox txtRegistName;
		protected global::System.Web.UI.WebControls.TextBox txtHeadImgPath;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtSecurityId;
		protected global::System.Web.UI.WebControls.TextBox txtSecurityAnswer;
		protected global::System.Web.UI.WebControls.TextBox txtRandomStr;
		protected global::System.Web.UI.WebControls.TextBox txtAppType;
		protected global::System.Web.UI.WebControls.TextBox txtPayIntegration;
		protected global::System.Web.UI.WebControls.TextBox txtTotalMoney;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
