//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.UserRegist {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblRegistPhone;
	protected global::System.Web.UI.WebControls.Label lblPassWord;
	protected global::System.Web.UI.WebControls.Label lblIdentityCard;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblRegistName;
	protected global::System.Web.UI.WebControls.Label lblHeadImgPath;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblSecurityId;
	protected global::System.Web.UI.WebControls.Label lblSecurityAnswer;
	protected global::System.Web.UI.WebControls.Label lblRandomStr;
	protected global::System.Web.UI.WebControls.Label lblAppType;
	protected global::System.Web.UI.WebControls.Label lblPayIntegration;
	protected global::System.Web.UI.WebControls.Label lblTotalMoney;


       
    }
}
