//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MultiUser {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtUserName;
		protected global::System.Web.UI.WebControls.TextBox txtDeptID;
		protected global::System.Web.UI.WebControls.TextBox txtCardId;
		protected global::System.Web.UI.WebControls.TextBox txtCardSector;
		protected global::System.Web.UI.WebControls.TextBox txtCardSn;
		protected global::System.Web.UI.WebControls.TextBox txtMark;
		protected global::System.Web.UI.WebControls.TextBox txtSex;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtPaperType;
		protected global::System.Web.UI.WebControls.TextBox txtPaperNo;
		protected global::System.Web.UI.WebControls.TextBox txtuAccount;
		protected global::System.Web.UI.WebControls.TextBox txtOpenTime;
		protected global::System.Web.UI.WebControls.TextBox txtValidDate;
		protected global::System.Web.UI.WebControls.TextBox txtLastMoney;
		protected global::System.Web.UI.WebControls.TextBox txtTotalMoney;
		protected global::System.Web.UI.WebControls.TextBox txtReMark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
