//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.OperationTotal {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtTID;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtPayID;
		protected global::System.Web.UI.WebControls.TextBox txtBeginMonth;
		protected global::System.Web.UI.WebControls.TextBox txtBeginNumber;
		protected global::System.Web.UI.WebControls.TextBox txtEndMonth;
		protected global::System.Web.UI.WebControls.TextBox txtEndNumber;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtPrice2;
		protected global::System.Web.UI.WebControls.TextBox txtPrice3;
		protected global::System.Web.UI.WebControls.TextBox txtFareMoney;
		protected global::System.Web.UI.WebControls.TextBox txtPayMark;
		protected global::System.Web.UI.WebControls.TextBox txtOperType;
		protected global::System.Web.UI.WebControls.TextBox txtOperDate;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtopermonth;
		protected global::System.Web.UI.WebControls.TextBox txtPriceUnit;
		protected global::System.Web.UI.WebControls.TextBox txtOperationName;
		protected global::System.Web.UI.WebControls.TextBox txtDivid1;
		protected global::System.Web.UI.WebControls.TextBox txtDivid2;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber1;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber2;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber3;
		protected global::System.Web.UI.WebControls.TextBox txtAdditionNum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
