//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.OperationTotal {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblTID;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblPayID;
	protected global::System.Web.UI.WebControls.Label lblBeginMonth;
	protected global::System.Web.UI.WebControls.Label lblBeginNumber;
	protected global::System.Web.UI.WebControls.Label lblEndMonth;
	protected global::System.Web.UI.WebControls.Label lblEndNumber;
	protected global::System.Web.UI.WebControls.Label lblUseNumber;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeName;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblPrice2;
	protected global::System.Web.UI.WebControls.Label lblPrice3;
	protected global::System.Web.UI.WebControls.Label lblFareMoney;
	protected global::System.Web.UI.WebControls.Label lblPayMark;
	protected global::System.Web.UI.WebControls.Label lblOperType;
	protected global::System.Web.UI.WebControls.Label lblOperDate;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblopermonth;
	protected global::System.Web.UI.WebControls.Label lblPriceUnit;
	protected global::System.Web.UI.WebControls.Label lblOperationName;
	protected global::System.Web.UI.WebControls.Label lblDivid1;
	protected global::System.Web.UI.WebControls.Label lblDivid2;
	protected global::System.Web.UI.WebControls.Label lblUseNumber1;
	protected global::System.Web.UI.WebControls.Label lblUseNumber2;
	protected global::System.Web.UI.WebControls.Label lblUseNumber3;
	protected global::System.Web.UI.WebControls.Label lblAdditionNum;


       
    }
}
