//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.InvoiceTemplate {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblTemplateID;
	protected global::System.Web.UI.WebControls.Label lblTemplateName;
	protected global::System.Web.UI.WebControls.Label lblTemplatePath;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblTemplateFile;
	protected global::System.Web.UI.WebControls.Label lblLastOperTime;
	protected global::System.Web.UI.WebControls.Label lblLastOperatorId;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
