//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterRouteInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMeterAddr;
		protected global::System.Web.UI.WebControls.TextBox txtMeterNo;
		protected global::System.Web.UI.WebControls.TextBox txtNode1;
		protected global::System.Web.UI.WebControls.TextBox txtDepth1;
		protected global::System.Web.UI.WebControls.TextBox txtNode2;
		protected global::System.Web.UI.WebControls.TextBox txtDepth2;
		protected global::System.Web.UI.WebControls.TextBox txtNode3;
		protected global::System.Web.UI.WebControls.TextBox txtDepth3;
		protected global::System.Web.UI.WebControls.TextBox txtNode4;
		protected global::System.Web.UI.WebControls.TextBox txtDepth4;
		protected global::System.Web.UI.WebControls.CheckBox chkResult;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorId;
		protected global::System.Web.UI.WebControls.TextBox txtMeterId;
		protected global::System.Web.UI.WebControls.TextBox txtReadTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
