//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterRouteInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblMeterAddr;
	protected global::System.Web.UI.WebControls.Label lblMeterNo;
	protected global::System.Web.UI.WebControls.Label lblNode1;
	protected global::System.Web.UI.WebControls.Label lblDepth1;
	protected global::System.Web.UI.WebControls.Label lblNode2;
	protected global::System.Web.UI.WebControls.Label lblDepth2;
	protected global::System.Web.UI.WebControls.Label lblNode3;
	protected global::System.Web.UI.WebControls.Label lblDepth3;
	protected global::System.Web.UI.WebControls.Label lblNode4;
	protected global::System.Web.UI.WebControls.Label lblDepth4;
	protected global::System.Web.UI.WebControls.Label lblResult;
	protected global::System.Web.UI.WebControls.Label lblCollectorId;
	protected global::System.Web.UI.WebControls.Label lblMeterId;
	protected global::System.Web.UI.WebControls.Label lblReadTime;


       
    }
}
