//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FailureMessage {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtFailID;
		protected global::System.Web.UI.WebControls.TextBox txtType;
		protected global::System.Web.UI.WebControls.TextBox txtFlag;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtUpLoadTime;
		protected global::System.Web.UI.WebControls.TextBox txtSize;
		protected global::System.Web.UI.WebControls.TextBox txtPattern;
		protected global::System.Web.UI.WebControls.TextBox txtUrl;
		protected global::System.Web.UI.WebControls.TextBox txtLocationX;
		protected global::System.Web.UI.WebControls.TextBox txtLocationY;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
