//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FailureMessage {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblFailID;
	protected global::System.Web.UI.WebControls.Label lblType;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblUpLoadTime;
	protected global::System.Web.UI.WebControls.Label lblSize;
	protected global::System.Web.UI.WebControls.Label lblPattern;
	protected global::System.Web.UI.WebControls.Label lblUrl;
	protected global::System.Web.UI.WebControls.Label lblLocationX;
	protected global::System.Web.UI.WebControls.Label lblLocationY;


       
    }
}
