//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PhoneMessage {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtSoftName;
		protected global::System.Web.UI.WebControls.TextBox txtBrands;
		protected global::System.Web.UI.WebControls.TextBox txtModel;
		protected global::System.Web.UI.WebControls.TextBox txtVersion;
		protected global::System.Web.UI.WebControls.TextBox txtBlueToothVer;
		protected global::System.Web.UI.WebControls.TextBox txtSDKVer;
		protected global::System.Web.UI.WebControls.TextBox txtIMEI;
		protected global::System.Web.UI.WebControls.TextBox txtCPU;
		protected global::System.Web.UI.WebControls.TextBox txtMemory;
		protected global::System.Web.UI.WebControls.TextBox txtResolution;
		protected global::System.Web.UI.WebControls.TextBox txtFirstLoginDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
