//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PhoneMessage {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblSoftName;
	protected global::System.Web.UI.WebControls.Label lblBrands;
	protected global::System.Web.UI.WebControls.Label lblModel;
	protected global::System.Web.UI.WebControls.Label lblVersion;
	protected global::System.Web.UI.WebControls.Label lblBlueToothVer;
	protected global::System.Web.UI.WebControls.Label lblSDKVer;
	protected global::System.Web.UI.WebControls.Label lblIMEI;
	protected global::System.Web.UI.WebControls.Label lblCPU;
	protected global::System.Web.UI.WebControls.Label lblMemory;
	protected global::System.Web.UI.WebControls.Label lblResolution;
	protected global::System.Web.UI.WebControls.Label lblFirstLoginDate;


       
    }
}
