//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Menus {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblMenuID;
		protected global::System.Web.UI.WebControls.TextBox txtUpperID;
		protected global::System.Web.UI.WebControls.TextBox txtMenuName;
		protected global::System.Web.UI.WebControls.TextBox txtUrlAddr;
		protected global::System.Web.UI.WebControls.TextBox txtUrlTarget;
		protected global::System.Web.UI.WebControls.TextBox txtImageUrl;
		protected global::System.Web.UI.WebControls.TextBox txtFlag;
		protected global::System.Web.UI.WebControls.TextBox txtOrdernum;
		protected global::System.Web.UI.WebControls.TextBox txtSystemNum;
		protected global::System.Web.UI.WebControls.TextBox txtPayType;
		protected global::System.Web.UI.WebControls.TextBox txtReMark;
		protected global::System.Web.UI.WebControls.TextBox txtPayTypeBak;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
