//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Menus {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblMenuID;
	protected global::System.Web.UI.WebControls.Label lblUpperID;
	protected global::System.Web.UI.WebControls.Label lblMenuName;
	protected global::System.Web.UI.WebControls.Label lblUrlAddr;
	protected global::System.Web.UI.WebControls.Label lblUrlTarget;
	protected global::System.Web.UI.WebControls.Label lblImageUrl;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblOrdernum;
	protected global::System.Web.UI.WebControls.Label lblSystemNum;
	protected global::System.Web.UI.WebControls.Label lblPayType;
	protected global::System.Web.UI.WebControls.Label lblReMark;
	protected global::System.Web.UI.WebControls.Label lblPayTypeBak;


       
    }
}
