//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.InvoiceRangeInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBatchId;
	protected global::System.Web.UI.WebControls.Label lblInCode;
	protected global::System.Web.UI.WebControls.Label lblStartNum;
	protected global::System.Web.UI.WebControls.Label lblEndNum;
	protected global::System.Web.UI.WebControls.Label lblOperatorName;
	protected global::System.Web.UI.WebControls.Label lblGetDateTime;
	protected global::System.Web.UI.WebControls.Label lblInDate;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
