//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Hosts {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCollectorID;
		protected global::System.Web.UI.WebControls.TextBox txtHostID;
		protected global::System.Web.UI.WebControls.TextBox txtHostName;
		protected global::System.Web.UI.WebControls.TextBox txtHostAddr;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtflag;
		protected global::System.Web.UI.WebControls.TextBox txtLimitNum;
		protected global::System.Web.UI.WebControls.TextBox txtHostComType;
		protected global::System.Web.UI.WebControls.TextBox txtHostType;
		protected global::System.Web.UI.WebControls.TextBox txtHostRDate;
		protected global::System.Web.UI.WebControls.TextBox txtDownloadFlag;
		protected global::System.Web.UI.WebControls.TextBox txtPowerType;
		protected global::System.Web.UI.WebControls.TextBox txtHostNo;
		protected global::System.Web.UI.WebControls.TextBox txtHostLimitNum;
		protected global::System.Web.UI.WebControls.TextBox txtIsRelay;
		protected global::System.Web.UI.WebControls.TextBox txtIsDownMeterType;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
