//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Hosts {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCollectorID;
	protected global::System.Web.UI.WebControls.Label lblHostID;
	protected global::System.Web.UI.WebControls.Label lblHostName;
	protected global::System.Web.UI.WebControls.Label lblHostAddr;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblflag;
	protected global::System.Web.UI.WebControls.Label lblLimitNum;
	protected global::System.Web.UI.WebControls.Label lblHostComType;
	protected global::System.Web.UI.WebControls.Label lblHostType;
	protected global::System.Web.UI.WebControls.Label lblHostRDate;
	protected global::System.Web.UI.WebControls.Label lblDownloadFlag;
	protected global::System.Web.UI.WebControls.Label lblPowerType;
	protected global::System.Web.UI.WebControls.Label lblHostNo;
	protected global::System.Web.UI.WebControls.Label lblHostLimitNum;
	protected global::System.Web.UI.WebControls.Label lblIsRelay;
	protected global::System.Web.UI.WebControls.Label lblIsDownMeterType;


       
    }
}
