//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterImageCutArea {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMeterId;
		protected global::System.Web.UI.WebControls.TextBox txtCameraNo;
		protected global::System.Web.UI.WebControls.TextBox txtCutLocationX;
		protected global::System.Web.UI.WebControls.TextBox txtCutLocationY;
		protected global::System.Web.UI.WebControls.TextBox txtCutWidth;
		protected global::System.Web.UI.WebControls.TextBox txtCutHeight;
		protected global::System.Web.UI.WebControls.TextBox txtLastOperDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
