//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Collectors {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblCollectorID;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorName;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorAddr;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorType;
		protected global::System.Web.UI.WebControls.TextBox txtDeptID;
		protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;
		protected global::System.Web.UI.WebControls.TextBox txtCollOverTime;
		protected global::System.Web.UI.WebControls.TextBox txtIPNumber;
		protected global::System.Web.UI.WebControls.TextBox txtPortNumber;
		protected global::System.Web.UI.WebControls.TextBox txtGprsCycle;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeDay;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeHour;
		protected global::System.Web.UI.WebControls.TextBox txtReadDay;
		protected global::System.Web.UI.WebControls.TextBox txtLoginDate;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateDate;
		protected global::System.Web.UI.WebControls.TextBox txtLoginIP;
		protected global::System.Web.UI.WebControls.TextBox txtLoginPort;
		protected global::System.Web.UI.WebControls.TextBox txtMark;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorVer;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorModel;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorAPN;
		protected global::System.Web.UI.WebControls.TextBox txtIsServerMode;
		protected global::System.Web.UI.WebControls.TextBox txtWorkTime;
		protected global::System.Web.UI.WebControls.TextBox txtNetWorkTime;
		protected global::System.Web.UI.WebControls.TextBox txtFactoryCode;
		protected global::System.Web.UI.WebControls.TextBox txtFramesType;
		protected global::System.Web.UI.WebControls.TextBox txtMeterAddrFormat;
		protected global::System.Web.UI.WebControls.TextBox txtGprsPhone;
		protected global::System.Web.UI.WebControls.TextBox txtExpireTime;
		protected global::System.Web.UI.WebControls.TextBox txtWorkMode;
		protected global::System.Web.UI.WebControls.TextBox txtLng;
		protected global::System.Web.UI.WebControls.TextBox txtLat;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
