//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Collectors {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblCollectorID;
	protected global::System.Web.UI.WebControls.Label lblCollectorName;
	protected global::System.Web.UI.WebControls.Label lblCollectorAddr;
	protected global::System.Web.UI.WebControls.Label lblCollectorType;
	protected global::System.Web.UI.WebControls.Label lblDeptID;
	protected global::System.Web.UI.WebControls.Label lblPhoneNumber;
	protected global::System.Web.UI.WebControls.Label lblCollOverTime;
	protected global::System.Web.UI.WebControls.Label lblIPNumber;
	protected global::System.Web.UI.WebControls.Label lblPortNumber;
	protected global::System.Web.UI.WebControls.Label lblGprsCycle;
	protected global::System.Web.UI.WebControls.Label lblFreezeDay;
	protected global::System.Web.UI.WebControls.Label lblFreezeHour;
	protected global::System.Web.UI.WebControls.Label lblReadDay;
	protected global::System.Web.UI.WebControls.Label lblLoginDate;
	protected global::System.Web.UI.WebControls.Label lblUpdateDate;
	protected global::System.Web.UI.WebControls.Label lblLoginIP;
	protected global::System.Web.UI.WebControls.Label lblLoginPort;
	protected global::System.Web.UI.WebControls.Label lblMark;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblCollectorVer;
	protected global::System.Web.UI.WebControls.Label lblCollectorModel;
	protected global::System.Web.UI.WebControls.Label lblCollectorAPN;
	protected global::System.Web.UI.WebControls.Label lblIsServerMode;
	protected global::System.Web.UI.WebControls.Label lblWorkTime;
	protected global::System.Web.UI.WebControls.Label lblNetWorkTime;
	protected global::System.Web.UI.WebControls.Label lblFactoryCode;
	protected global::System.Web.UI.WebControls.Label lblFramesType;
	protected global::System.Web.UI.WebControls.Label lblMeterAddrFormat;
	protected global::System.Web.UI.WebControls.Label lblGprsPhone;
	protected global::System.Web.UI.WebControls.Label lblExpireTime;
	protected global::System.Web.UI.WebControls.Label lblWorkMode;
	protected global::System.Web.UI.WebControls.Label lblLng;
	protected global::System.Web.UI.WebControls.Label lblLat;


       
    }
}
