//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FareItem {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblFareID;
		protected global::System.Web.UI.WebControls.TextBox txtCycNumber;
		protected global::System.Web.UI.WebControls.TextBox txtFareName;
		protected global::System.Web.UI.WebControls.TextBox txtFareMoney;
		protected global::System.Web.UI.WebControls.TextBox txtFareMemo;
		protected global::System.Web.UI.WebControls.TextBox txtFareMark;
		protected global::System.Web.UI.WebControls.TextBox txtPriceUnit;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
