//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.InvoiceList {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtInID;
		protected global::System.Web.UI.WebControls.TextBox txtInCode;
		protected global::System.Web.UI.WebControls.TextBox txtInNumber;
		protected global::System.Web.UI.WebControls.TextBox txtSiteID;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorName;
		protected global::System.Web.UI.WebControls.TextBox txtGetDate;
		protected global::System.Web.UI.WebControls.TextBox txtPayID;
		protected global::System.Web.UI.WebControls.TextBox txtPrintDate;
		protected global::System.Web.UI.WebControls.TextBox txtInMoney;
		protected global::System.Web.UI.WebControls.TextBox txtInMark;
		protected global::System.Web.UI.WebControls.TextBox txtSendMark;
		protected global::System.Web.UI.WebControls.TextBox txtSendDate;
		protected global::System.Web.UI.WebControls.TextBox txtprintMan;
		protected global::System.Web.UI.WebControls.TextBox txtzfDate;
		protected global::System.Web.UI.WebControls.TextBox txtzfInCode;
		protected global::System.Web.UI.WebControls.TextBox txtzfInNumber;
		protected global::System.Web.UI.WebControls.TextBox txtUName;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
