//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.InvoiceList {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblInID;
	protected global::System.Web.UI.WebControls.Label lblInCode;
	protected global::System.Web.UI.WebControls.Label lblInNumber;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblOperatorName;
	protected global::System.Web.UI.WebControls.Label lblGetDate;
	protected global::System.Web.UI.WebControls.Label lblPayID;
	protected global::System.Web.UI.WebControls.Label lblPrintDate;
	protected global::System.Web.UI.WebControls.Label lblInMoney;
	protected global::System.Web.UI.WebControls.Label lblInMark;
	protected global::System.Web.UI.WebControls.Label lblSendMark;
	protected global::System.Web.UI.WebControls.Label lblSendDate;
	protected global::System.Web.UI.WebControls.Label lblprintMan;
	protected global::System.Web.UI.WebControls.Label lblzfDate;
	protected global::System.Web.UI.WebControls.Label lblzfInCode;
	protected global::System.Web.UI.WebControls.Label lblzfInNumber;
	protected global::System.Web.UI.WebControls.Label lblUName;


       
    }
}
