//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ManageUser {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUsersID;
		protected global::System.Web.UI.WebControls.TextBox txtManageFareID;
		protected global::System.Web.UI.WebControls.TextBox txtChargeDate;
		protected global::System.Web.UI.WebControls.TextBox txtLastDate;
		protected global::System.Web.UI.WebControls.TextBox txtReMark;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
