//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PriceTypeDev {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtLateFeeRate;
		protected global::System.Web.UI.WebControls.TextBox txtLateFeeDate;
		protected global::System.Web.UI.WebControls.TextBox txtLateFeeBase;
		protected global::System.Web.UI.WebControls.TextBox txtICMonth;
		protected global::System.Web.UI.WebControls.TextBox txtICMaxBuy;
		protected global::System.Web.UI.WebControls.TextBox txtICAmount;
		protected global::System.Web.UI.WebControls.TextBox txtICMonthBuy;
		protected global::System.Web.UI.WebControls.TextBox txtICDayAvg;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
