//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PriceTypeDev {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPriceTypeID;
	protected global::System.Web.UI.WebControls.Label lblLateFeeRate;
	protected global::System.Web.UI.WebControls.Label lblLateFeeDate;
	protected global::System.Web.UI.WebControls.Label lblLateFeeBase;
	protected global::System.Web.UI.WebControls.Label lblICMonth;
	protected global::System.Web.UI.WebControls.Label lblICMaxBuy;
	protected global::System.Web.UI.WebControls.Label lblICAmount;
	protected global::System.Web.UI.WebControls.Label lblICMonthBuy;
	protected global::System.Web.UI.WebControls.Label lblICDayAvg;


       
    }
}
