//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ManageFareList {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUsersID;
		protected global::System.Web.UI.WebControls.TextBox txtManageFareID;
		protected global::System.Web.UI.WebControls.TextBox txtLastMonth;
		protected global::System.Web.UI.WebControls.TextBox txtThisMonth;
		protected global::System.Web.UI.WebControls.TextBox txtManageFarePrice;
		protected global::System.Web.UI.WebControls.TextBox txtOperMoney;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtOperDate;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtOperID;
		protected global::System.Web.UI.WebControls.TextBox txtOperType;
		protected global::System.Web.UI.WebControls.TextBox txtRcvFareNum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
