//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Meters {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMeterTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtMeterAddr;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorID;
		protected global::System.Web.UI.WebControls.TextBox txtHostID;
		protected global::System.Web.UI.WebControls.TextBox txtUsersID;
		protected global::System.Web.UI.WebControls.TextBox txtCardType;
		protected global::System.Web.UI.WebControls.TextBox txtCardID;
		protected global::System.Web.UI.WebControls.TextBox txtCardSector;
		protected global::System.Web.UI.WebControls.TextBox txtTotalMoney;
		protected global::System.Web.UI.WebControls.TextBox txtTotalInt;
		protected global::System.Web.UI.WebControls.TextBox txtTotalBase;
		protected global::System.Web.UI.WebControls.TextBox txtLastMoney;
		protected global::System.Web.UI.WebControls.TextBox txtLastInt;
		protected global::System.Web.UI.WebControls.TextBox txtLastBase;
		protected global::System.Web.UI.WebControls.TextBox txtMark;
		protected global::System.Web.UI.WebControls.TextBox txtMeterBase;
		protected global::System.Web.UI.WebControls.TextBox txtMeterVerify;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtMeterDate;
		protected global::System.Web.UI.WebControls.TextBox txtMeterNumber;
		protected global::System.Web.UI.WebControls.TextBox txtInstallDate;
		protected global::System.Web.UI.WebControls.TextBox txtInstallAddr;
		protected global::System.Web.UI.WebControls.TextBox txtConstant;
		protected global::System.Web.UI.WebControls.TextBox txtMutual;
		protected global::System.Web.UI.WebControls.TextBox txtCoefficient;
		protected global::System.Web.UI.WebControls.TextBox txtLastCalNumber;
		protected global::System.Web.UI.WebControls.TextBox txtLastCalMonth;
		protected global::System.Web.UI.WebControls.TextBox txtLastReadNumber;
		protected global::System.Web.UI.WebControls.TextBox txtPayType;
		protected global::System.Web.UI.WebControls.TextBox txtModalid;
		protected global::System.Web.UI.WebControls.TextBox txtXPower;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtWorkerID;
		protected global::System.Web.UI.WebControls.TextBox txtDayUseNum;
		protected global::System.Web.UI.WebControls.TextBox txtMf1Sn;
		protected global::System.Web.UI.WebControls.TextBox txtAlarmDis;
		protected global::System.Web.UI.WebControls.TextBox txtAlarmShut;
		protected global::System.Web.UI.WebControls.TextBox txtMeterNo;
		protected global::System.Web.UI.WebControls.TextBox txtRelayed;
		protected global::System.Web.UI.WebControls.TextBox txtRouteLen;
		protected global::System.Web.UI.WebControls.TextBox txtRouteInfo;
		protected global::System.Web.UI.WebControls.TextBox txtFloor;
		protected global::System.Web.UI.WebControls.TextBox txtGroupID;
		protected global::System.Web.UI.WebControls.TextBox txtLastCur;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceType;
		protected global::System.Web.UI.WebControls.TextBox txtPercent0;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeName1;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID1;
		protected global::System.Web.UI.WebControls.TextBox txtPercent1;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID2;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeName2;
		protected global::System.Web.UI.WebControls.TextBox txtPercent2;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID3;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeName3;
		protected global::System.Web.UI.WebControls.TextBox txtPercent3;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID4;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeName4;
		protected global::System.Web.UI.WebControls.TextBox txtPercent4;
		protected global::System.Web.UI.WebControls.TextBox txtMeterMC;
		protected global::System.Web.UI.WebControls.TextBox txtuAccount;
		protected global::System.Web.UI.WebControls.TextBox txtIsSend;
		protected global::System.Web.UI.WebControls.TextBox txtHostAddr;
		protected global::System.Web.UI.WebControls.TextBox txtLastReadDate;
		protected global::System.Web.UI.WebControls.TextBox txtOverUse;
		protected global::System.Web.UI.WebControls.TextBox txtDownloadFlag;
		protected global::System.Web.UI.WebControls.TextBox txtTotalGroup;
		protected global::System.Web.UI.WebControls.TextBox txtCurrentGroup;
		protected global::System.Web.UI.WebControls.TextBox txtLastRecordNo;
		protected global::System.Web.UI.WebControls.TextBox txtBalanced;
		protected global::System.Web.UI.WebControls.TextBox txtMaxFill;
		protected global::System.Web.UI.WebControls.TextBox txtMinRem;
		protected global::System.Web.UI.WebControls.TextBox txtOverMoney;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeMode;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeDay;
		protected global::System.Web.UI.WebControls.TextBox txtPlasticInfo;
		protected global::System.Web.UI.WebControls.TextBox txtUseMeterDosage;
		protected global::System.Web.UI.WebControls.TextBox txtShutValveStaffId;
		protected global::System.Web.UI.WebControls.TextBox txtInstallStaffId;
		protected global::System.Web.UI.WebControls.TextBox txtCheckDate;
		protected global::System.Web.UI.WebControls.TextBox txtTagID;
		protected global::System.Web.UI.WebControls.TextBox txtBookID;
		protected global::System.Web.UI.WebControls.TextBox txtLocationX;
		protected global::System.Web.UI.WebControls.TextBox txtLocationY;
		protected global::System.Web.UI.WebControls.TextBox txtBookNum;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtImagePath;
		protected global::System.Web.UI.WebControls.TextBox txtBindTime;
		protected global::System.Web.UI.WebControls.TextBox txtCardFlag;
		protected global::System.Web.UI.WebControls.TextBox txtPriceSetNo;
		protected global::System.Web.UI.WebControls.TextBox txtCollectorReadDate;
		protected global::System.Web.UI.WebControls.TextBox txtBuyGasNum;
		protected global::System.Web.UI.WebControls.TextBox txtMeterPackageCode;
		protected global::System.Web.UI.WebControls.TextBox txtHighWarnMoney;
		protected global::System.Web.UI.WebControls.TextBox txtMiddleWarnMoney;
		protected global::System.Web.UI.WebControls.TextBox txtLowWarnMoney;
		protected global::System.Web.UI.WebControls.TextBox txtLowerReserve;
		protected global::System.Web.UI.WebControls.TextBox txtIsInstall;
		protected global::System.Web.UI.WebControls.TextBox txtIsOpen;
		protected global::System.Web.UI.WebControls.TextBox txtCreateTime;
		protected global::System.Web.UI.WebControls.TextBox txtOpenTime;
		protected global::System.Web.UI.WebControls.TextBox txtSyncFlag;
		protected global::System.Web.UI.WebControls.TextBox txtCameraCount;
		protected global::System.Web.UI.WebControls.TextBox txtMeterPhone;
		protected global::System.Web.UI.WebControls.TextBox txtDevEUI;
		protected global::System.Web.UI.WebControls.TextBox txtIMEI;
		protected global::System.Web.UI.WebControls.TextBox txtUploadOffsetTime;
		protected global::System.Web.UI.WebControls.CheckBox chkIsUseAlertClose;
		protected global::System.Web.UI.WebControls.TextBox txtDiscountsNum;
		protected global::System.Web.UI.WebControls.TextBox txtMeterKey;
		protected global::System.Web.UI.WebControls.TextBox txtIsBlack;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
