//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Meters {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblMeterTypeID;
	protected global::System.Web.UI.WebControls.Label lblMeterAddr;
	protected global::System.Web.UI.WebControls.Label lblCollectorID;
	protected global::System.Web.UI.WebControls.Label lblHostID;
	protected global::System.Web.UI.WebControls.Label lblUsersID;
	protected global::System.Web.UI.WebControls.Label lblCardType;
	protected global::System.Web.UI.WebControls.Label lblCardID;
	protected global::System.Web.UI.WebControls.Label lblCardSector;
	protected global::System.Web.UI.WebControls.Label lblTotalMoney;
	protected global::System.Web.UI.WebControls.Label lblTotalInt;
	protected global::System.Web.UI.WebControls.Label lblTotalBase;
	protected global::System.Web.UI.WebControls.Label lblLastMoney;
	protected global::System.Web.UI.WebControls.Label lblLastInt;
	protected global::System.Web.UI.WebControls.Label lblLastBase;
	protected global::System.Web.UI.WebControls.Label lblMark;
	protected global::System.Web.UI.WebControls.Label lblMeterBase;
	protected global::System.Web.UI.WebControls.Label lblMeterVerify;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID;
	protected global::System.Web.UI.WebControls.Label lblMeterDate;
	protected global::System.Web.UI.WebControls.Label lblMeterNumber;
	protected global::System.Web.UI.WebControls.Label lblInstallDate;
	protected global::System.Web.UI.WebControls.Label lblInstallAddr;
	protected global::System.Web.UI.WebControls.Label lblConstant;
	protected global::System.Web.UI.WebControls.Label lblMutual;
	protected global::System.Web.UI.WebControls.Label lblCoefficient;
	protected global::System.Web.UI.WebControls.Label lblLastCalNumber;
	protected global::System.Web.UI.WebControls.Label lblLastCalMonth;
	protected global::System.Web.UI.WebControls.Label lblLastReadNumber;
	protected global::System.Web.UI.WebControls.Label lblPayType;
	protected global::System.Web.UI.WebControls.Label lblModalid;
	protected global::System.Web.UI.WebControls.Label lblXPower;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblWorkerID;
	protected global::System.Web.UI.WebControls.Label lblDayUseNum;
	protected global::System.Web.UI.WebControls.Label lblMf1Sn;
	protected global::System.Web.UI.WebControls.Label lblAlarmDis;
	protected global::System.Web.UI.WebControls.Label lblAlarmShut;
	protected global::System.Web.UI.WebControls.Label lblMeterNo;
	protected global::System.Web.UI.WebControls.Label lblRelayed;
	protected global::System.Web.UI.WebControls.Label lblRouteLen;
	protected global::System.Web.UI.WebControls.Label lblRouteInfo;
	protected global::System.Web.UI.WebControls.Label lblFloor;
	protected global::System.Web.UI.WebControls.Label lblGroupID;
	protected global::System.Web.UI.WebControls.Label lblLastCur;
	protected global::System.Web.UI.WebControls.Label lblInvoiceType;
	protected global::System.Web.UI.WebControls.Label lblPercent0;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeName1;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID1;
	protected global::System.Web.UI.WebControls.Label lblPercent1;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID2;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeName2;
	protected global::System.Web.UI.WebControls.Label lblPercent2;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID3;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeName3;
	protected global::System.Web.UI.WebControls.Label lblPercent3;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID4;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeName4;
	protected global::System.Web.UI.WebControls.Label lblPercent4;
	protected global::System.Web.UI.WebControls.Label lblMeterMC;
	protected global::System.Web.UI.WebControls.Label lbluAccount;
	protected global::System.Web.UI.WebControls.Label lblIsSend;
	protected global::System.Web.UI.WebControls.Label lblHostAddr;
	protected global::System.Web.UI.WebControls.Label lblLastReadDate;
	protected global::System.Web.UI.WebControls.Label lblOverUse;
	protected global::System.Web.UI.WebControls.Label lblDownloadFlag;
	protected global::System.Web.UI.WebControls.Label lblTotalGroup;
	protected global::System.Web.UI.WebControls.Label lblCurrentGroup;
	protected global::System.Web.UI.WebControls.Label lblLastRecordNo;
	protected global::System.Web.UI.WebControls.Label lblBalanced;
	protected global::System.Web.UI.WebControls.Label lblMaxFill;
	protected global::System.Web.UI.WebControls.Label lblMinRem;
	protected global::System.Web.UI.WebControls.Label lblOverMoney;
	protected global::System.Web.UI.WebControls.Label lblFreezeMode;
	protected global::System.Web.UI.WebControls.Label lblFreezeDay;
	protected global::System.Web.UI.WebControls.Label lblPlasticInfo;
	protected global::System.Web.UI.WebControls.Label lblUseMeterDosage;
	protected global::System.Web.UI.WebControls.Label lblShutValveStaffId;
	protected global::System.Web.UI.WebControls.Label lblInstallStaffId;
	protected global::System.Web.UI.WebControls.Label lblCheckDate;
	protected global::System.Web.UI.WebControls.Label lblTagID;
	protected global::System.Web.UI.WebControls.Label lblBookID;
	protected global::System.Web.UI.WebControls.Label lblLocationX;
	protected global::System.Web.UI.WebControls.Label lblLocationY;
	protected global::System.Web.UI.WebControls.Label lblBookNum;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblImagePath;
	protected global::System.Web.UI.WebControls.Label lblBindTime;
	protected global::System.Web.UI.WebControls.Label lblCardFlag;
	protected global::System.Web.UI.WebControls.Label lblPriceSetNo;
	protected global::System.Web.UI.WebControls.Label lblCollectorReadDate;
	protected global::System.Web.UI.WebControls.Label lblBuyGasNum;
	protected global::System.Web.UI.WebControls.Label lblMeterPackageCode;
	protected global::System.Web.UI.WebControls.Label lblHighWarnMoney;
	protected global::System.Web.UI.WebControls.Label lblMiddleWarnMoney;
	protected global::System.Web.UI.WebControls.Label lblLowWarnMoney;
	protected global::System.Web.UI.WebControls.Label lblLowerReserve;
	protected global::System.Web.UI.WebControls.Label lblIsInstall;
	protected global::System.Web.UI.WebControls.Label lblIsOpen;
	protected global::System.Web.UI.WebControls.Label lblCreateTime;
	protected global::System.Web.UI.WebControls.Label lblOpenTime;
	protected global::System.Web.UI.WebControls.Label lblSyncFlag;
	protected global::System.Web.UI.WebControls.Label lblCameraCount;
	protected global::System.Web.UI.WebControls.Label lblMeterPhone;
	protected global::System.Web.UI.WebControls.Label lblDevEUI;
	protected global::System.Web.UI.WebControls.Label lblIMEI;
	protected global::System.Web.UI.WebControls.Label lblUploadOffsetTime;
	protected global::System.Web.UI.WebControls.Label lblIsUseAlertClose;
	protected global::System.Web.UI.WebControls.Label lblDiscountsNum;
	protected global::System.Web.UI.WebControls.Label lblMeterKey;
	protected global::System.Web.UI.WebControls.Label lblIsBlack;


       
    }
}
