//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.InvoiceNumInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtDisId;
		protected global::System.Web.UI.WebControls.TextBox txtBatchId;
		protected global::System.Web.UI.WebControls.TextBox txtInCode;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceNum;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNum;
		protected global::System.Web.UI.WebControls.TextBox txtMark;
		protected global::System.Web.UI.WebControls.TextBox txtSubFlag;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtAssignOperator;
		protected global::System.Web.UI.WebControls.TextBox txtAssignDate;
		protected global::System.Web.UI.WebControls.TextBox txtOperDate;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
