//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.CompanyInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtCompanyName;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyNo;
		protected global::System.Web.UI.WebControls.TextBox txtPwd;
		protected global::System.Web.UI.WebControls.TextBox txtAuthorizationCode;
		protected global::System.Web.UI.WebControls.TextBox txtIDCode;
		protected global::System.Web.UI.WebControls.TextBox txtEFileCode;
		protected global::System.Web.UI.WebControls.TextBox txtTaxAgencyCode;
		protected global::System.Web.UI.WebControls.TextBox txtAgentMark;
		protected global::System.Web.UI.WebControls.TextBox txtProjectName;
		protected global::System.Web.UI.WebControls.TextBox txtProjectCode;
		protected global::System.Web.UI.WebControls.TextBox txtAccountBank;
		protected global::System.Web.UI.WebControls.TextBox txtAccountNumber;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyAddress;
		protected global::System.Web.UI.WebControls.TextBox txtCompanyPhone;
		protected global::System.Web.UI.WebControls.TextBox txtSleepTime;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
