//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.CompanyInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblCompanyName;
	protected global::System.Web.UI.WebControls.Label lblCompanyNo;
	protected global::System.Web.UI.WebControls.Label lblPwd;
	protected global::System.Web.UI.WebControls.Label lblAuthorizationCode;
	protected global::System.Web.UI.WebControls.Label lblIDCode;
	protected global::System.Web.UI.WebControls.Label lblEFileCode;
	protected global::System.Web.UI.WebControls.Label lblTaxAgencyCode;
	protected global::System.Web.UI.WebControls.Label lblAgentMark;
	protected global::System.Web.UI.WebControls.Label lblProjectName;
	protected global::System.Web.UI.WebControls.Label lblProjectCode;
	protected global::System.Web.UI.WebControls.Label lblAccountBank;
	protected global::System.Web.UI.WebControls.Label lblAccountNumber;
	protected global::System.Web.UI.WebControls.Label lblCompanyAddress;
	protected global::System.Web.UI.WebControls.Label lblCompanyPhone;
	protected global::System.Web.UI.WebControls.Label lblSleepTime;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;


       
    }
}
