//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.BookTaskInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtBookID;
		protected global::System.Web.UI.WebControls.TextBox txtReadDate;
		protected global::System.Web.UI.WebControls.TextBox txtBookCode;
		protected global::System.Web.UI.WebControls.TextBox txtBookName;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtRoutes;
		protected global::System.Web.UI.WebControls.TextBox txtUserNum;
		protected global::System.Web.UI.WebControls.TextBox txtFactNum;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
