//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.OperationFareDay {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOperID;
	protected global::System.Web.UI.WebControls.Label lblFareID;
	protected global::System.Web.UI.WebControls.Label lblFareTypeName;
	protected global::System.Web.UI.WebControls.Label lblFarePrice;
	protected global::System.Web.UI.WebControls.Label lblFareMoney;
	protected global::System.Web.UI.WebControls.Label lblFarePrice2;
	protected global::System.Web.UI.WebControls.Label lblFarePrice3;
	protected global::System.Web.UI.WebControls.Label lblDivid1;
	protected global::System.Web.UI.WebControls.Label lblDivid2;
	protected global::System.Web.UI.WebControls.Label lblUseNumber1;
	protected global::System.Web.UI.WebControls.Label lblUseNumber2;
	protected global::System.Web.UI.WebControls.Label lblUseNumber3;
	protected global::System.Web.UI.WebControls.Label lblExtData1;
	protected global::System.Web.UI.WebControls.Label lblExtData2;


       
    }
}
