//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MultiOperation {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblOperID;
		protected global::System.Web.UI.WebControls.TextBox txtMultiUserID;
		protected global::System.Web.UI.WebControls.TextBox txtCardID;
		protected global::System.Web.UI.WebControls.TextBox txtCardSector;
		protected global::System.Web.UI.WebControls.TextBox txtOperMoney;
		protected global::System.Web.UI.WebControls.TextBox txtLastBalance;
		protected global::System.Web.UI.WebControls.TextBox txtCurrentBalance;
		protected global::System.Web.UI.WebControls.TextBox txtTotalMoney;
		protected global::System.Web.UI.WebControls.TextBox txtOperType;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceCode;
		protected global::System.Web.UI.WebControls.TextBox txtOperDate;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceID;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceType;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
