//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FreezeMonthDosage {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtBeginMonth;
		protected global::System.Web.UI.WebControls.TextBox txtBeginNumber;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeMonth;
		protected global::System.Web.UI.WebControls.TextBox txtEndNumber;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber;
		protected global::System.Web.UI.WebControls.TextBox txtInsertDate;
		protected global::System.Web.UI.WebControls.TextBox txtUseActiveSharp;
		protected global::System.Web.UI.WebControls.TextBox txtUseActivePeak;
		protected global::System.Web.UI.WebControls.TextBox txtUseActiveShoulder;
		protected global::System.Web.UI.WebControls.TextBox txtUseActiveOffPeak;
		protected global::System.Web.UI.WebControls.TextBox txtSyncFlag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
