//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FreezeMonthDosage {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblBeginMonth;
	protected global::System.Web.UI.WebControls.Label lblBeginNumber;
	protected global::System.Web.UI.WebControls.Label lblFreezeMonth;
	protected global::System.Web.UI.WebControls.Label lblEndNumber;
	protected global::System.Web.UI.WebControls.Label lblUseNumber;
	protected global::System.Web.UI.WebControls.Label lblInsertDate;
	protected global::System.Web.UI.WebControls.Label lblUseActiveSharp;
	protected global::System.Web.UI.WebControls.Label lblUseActivePeak;
	protected global::System.Web.UI.WebControls.Label lblUseActiveShoulder;
	protected global::System.Web.UI.WebControls.Label lblUseActiveOffPeak;
	protected global::System.Web.UI.WebControls.Label lblSyncFlag;


       
    }
}
