//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.SwitchBookLog {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblBookIDBefore;
	protected global::System.Web.UI.WebControls.Label lblBookNumBefore;
	protected global::System.Web.UI.WebControls.Label lblBookIDAfter;
	protected global::System.Web.UI.WebControls.Label lblBookNumAfter;
	protected global::System.Web.UI.WebControls.Label lblOperTime;


       
    }
}
