//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.LogData {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblLogID;
	protected global::System.Web.UI.WebControls.Label lblLogTitle;
	protected global::System.Web.UI.WebControls.Label lblLogType;
	protected global::System.Web.UI.WebControls.Label lblLogDate;
	protected global::System.Web.UI.WebControls.Label lblLogMemo;
	protected global::System.Web.UI.WebControls.Label lblLogData;
	protected global::System.Web.UI.WebControls.Label lblLogOperator;


       
    }
}
