//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.UpConsume {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUpId;
	protected global::System.Web.UI.WebControls.Label lblCardId;
	protected global::System.Web.UI.WebControls.Label lblLostFreeNum;
	protected global::System.Web.UI.WebControls.Label lblSurplusMoney;
	protected global::System.Web.UI.WebControls.Label lblConsumeTime;
	protected global::System.Web.UI.WebControls.Label lblMeterid;
	protected global::System.Web.UI.WebControls.Label lblUseMoney;
	protected global::System.Web.UI.WebControls.Label lblInsDate;


       
    }
}
