//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.CollectServer {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblServerId;
	protected global::System.Web.UI.WebControls.Label lblServerName;
	protected global::System.Web.UI.WebControls.Label lblServerType;
	protected global::System.Web.UI.WebControls.Label lblServerIp;
	protected global::System.Web.UI.WebControls.Label lblWcfUrl;
	protected global::System.Web.UI.WebControls.Label lblOperTime;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblPort;


       
    }
}
