//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterModal {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblModalid;
	protected global::System.Web.UI.WebControls.Label lblModalname;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblUseProtocol;
	protected global::System.Web.UI.WebControls.Label lblFactoryCode;
	protected global::System.Web.UI.WebControls.Label lblFactoryName;
	protected global::System.Web.UI.WebControls.Label lblMaxValue;
	protected global::System.Web.UI.WebControls.Label lblMaxYear;
	protected global::System.Web.UI.WebControls.Label lblCaliber;
	protected global::System.Web.UI.WebControls.Label lblMaxFlow;
	protected global::System.Web.UI.WebControls.Label lblMeterHeaderType;
	protected global::System.Web.UI.WebControls.Label lblMeterStatusCode;


       
    }
}
