//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PriceType {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtMeterTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtPriceNo;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtPrice2;
		protected global::System.Web.UI.WebControls.TextBox txtPrice3;
		protected global::System.Web.UI.WebControls.TextBox txtDivid1;
		protected global::System.Web.UI.WebControls.TextBox txtDivid2;
		protected global::System.Web.UI.WebControls.TextBox txtPriceUnit;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtPrice4;
		protected global::System.Web.UI.WebControls.TextBox txtPrice5;
		protected global::System.Web.UI.WebControls.TextBox txtPrice6;
		protected global::System.Web.UI.WebControls.TextBox txtDivid3;
		protected global::System.Web.UI.WebControls.TextBox txtDivid4;
		protected global::System.Web.UI.WebControls.TextBox txtDivid5;
		protected global::System.Web.UI.WebControls.TextBox txtExeDate;
		protected global::System.Web.UI.WebControls.TextBox txtSetNo;
		protected global::System.Web.UI.WebControls.TextBox txtSuiteNo;
		protected global::System.Web.UI.WebControls.TextBox txtGroupPriceNo;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeCode;
		protected global::System.Web.UI.WebControls.TextBox txtIsStartStar;
		protected global::System.Web.UI.WebControls.TextBox txtIsStartPeople;
		protected global::System.Web.UI.WebControls.TextBox txtPeopleCheck;
		protected global::System.Web.UI.WebControls.TextBox txtMaxPeople;
		protected global::System.Web.UI.WebControls.TextBox txtAddUseNumber;
		protected global::System.Web.UI.WebControls.TextBox txtStarsLevel;
		protected global::System.Web.UI.WebControls.TextBox txtStarsPeriod;
		protected global::System.Web.UI.WebControls.TextBox txtStarsCorrected;
		protected global::System.Web.UI.WebControls.TextBox txtIsStartArea;
		protected global::System.Web.UI.WebControls.TextBox txtCoefficient;
		protected global::System.Web.UI.WebControls.TextBox txtCalculateDay;
		protected global::System.Web.UI.WebControls.TextBox txtStarsAreaWay;
		protected global::System.Web.UI.WebControls.TextBox txtStarsByUser;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
