//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PriceType {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblPriceTypeID;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeName;
	protected global::System.Web.UI.WebControls.Label lblMeterTypeID;
	protected global::System.Web.UI.WebControls.Label lblPriceNo;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblPrice2;
	protected global::System.Web.UI.WebControls.Label lblPrice3;
	protected global::System.Web.UI.WebControls.Label lblDivid1;
	protected global::System.Web.UI.WebControls.Label lblDivid2;
	protected global::System.Web.UI.WebControls.Label lblPriceUnit;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblPrice4;
	protected global::System.Web.UI.WebControls.Label lblPrice5;
	protected global::System.Web.UI.WebControls.Label lblPrice6;
	protected global::System.Web.UI.WebControls.Label lblDivid3;
	protected global::System.Web.UI.WebControls.Label lblDivid4;
	protected global::System.Web.UI.WebControls.Label lblDivid5;
	protected global::System.Web.UI.WebControls.Label lblExeDate;
	protected global::System.Web.UI.WebControls.Label lblSetNo;
	protected global::System.Web.UI.WebControls.Label lblSuiteNo;
	protected global::System.Web.UI.WebControls.Label lblGroupPriceNo;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeCode;
	protected global::System.Web.UI.WebControls.Label lblIsStartStar;
	protected global::System.Web.UI.WebControls.Label lblIsStartPeople;
	protected global::System.Web.UI.WebControls.Label lblPeopleCheck;
	protected global::System.Web.UI.WebControls.Label lblMaxPeople;
	protected global::System.Web.UI.WebControls.Label lblAddUseNumber;
	protected global::System.Web.UI.WebControls.Label lblStarsLevel;
	protected global::System.Web.UI.WebControls.Label lblStarsPeriod;
	protected global::System.Web.UI.WebControls.Label lblStarsCorrected;
	protected global::System.Web.UI.WebControls.Label lblIsStartArea;
	protected global::System.Web.UI.WebControls.Label lblCoefficient;
	protected global::System.Web.UI.WebControls.Label lblCalculateDay;
	protected global::System.Web.UI.WebControls.Label lblStarsAreaWay;
	protected global::System.Web.UI.WebControls.Label lblStarsByUser;


       
    }
}
