//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FailureInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtFailurePhone;
		protected global::System.Web.UI.WebControls.TextBox txtFailureMan;
		protected global::System.Web.UI.WebControls.TextBox txtFailureMemo;
		protected global::System.Web.UI.WebControls.TextBox txtFailureType;
		protected global::System.Web.UI.WebControls.TextBox txtFailureRegTime;
		protected global::System.Web.UI.WebControls.TextBox txtFailureRegType;
		protected global::System.Web.UI.WebControls.TextBox txtDisposeMan;
		protected global::System.Web.UI.WebControls.TextBox txtDisposeMemo;
		protected global::System.Web.UI.WebControls.TextBox txtDisposeStatus;
		protected global::System.Web.UI.WebControls.TextBox txtDisposeTime;
		protected global::System.Web.UI.WebControls.CheckBox chksel;
		protected global::System.Web.UI.WebControls.TextBox txtFailureCode;
		protected global::System.Web.UI.WebControls.TextBox txtAppointMan;
		protected global::System.Web.UI.WebControls.TextBox txtAppointManPhone;
		protected global::System.Web.UI.WebControls.TextBox txtFailureSort;
		protected global::System.Web.UI.WebControls.TextBox txtUsersID;
		protected global::System.Web.UI.WebControls.TextBox txtUserCode;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
