//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FailureInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblFailurePhone;
	protected global::System.Web.UI.WebControls.Label lblFailureMan;
	protected global::System.Web.UI.WebControls.Label lblFailureMemo;
	protected global::System.Web.UI.WebControls.Label lblFailureType;
	protected global::System.Web.UI.WebControls.Label lblFailureRegTime;
	protected global::System.Web.UI.WebControls.Label lblFailureRegType;
	protected global::System.Web.UI.WebControls.Label lblDisposeMan;
	protected global::System.Web.UI.WebControls.Label lblDisposeMemo;
	protected global::System.Web.UI.WebControls.Label lblDisposeStatus;
	protected global::System.Web.UI.WebControls.Label lblDisposeTime;
	protected global::System.Web.UI.WebControls.Label lblsel;
	protected global::System.Web.UI.WebControls.Label lblFailureCode;
	protected global::System.Web.UI.WebControls.Label lblAppointMan;
	protected global::System.Web.UI.WebControls.Label lblAppointManPhone;
	protected global::System.Web.UI.WebControls.Label lblFailureSort;
	protected global::System.Web.UI.WebControls.Label lblUsersID;
	protected global::System.Web.UI.WebControls.Label lblUserCode;


       
    }
}
