//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterStateDictionary {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtStateCode;
		protected global::System.Web.UI.WebControls.TextBox txtStateName;
		protected global::System.Web.UI.WebControls.CheckBox chkEnable;
		protected global::System.Web.UI.WebControls.CheckBox chkIsShow;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNum;
		protected global::System.Web.UI.WebControls.TextBox txtReasion;
		protected global::System.Web.UI.WebControls.TextBox txtOperation;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
