//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterStateDictionary {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblStateCode;
	protected global::System.Web.UI.WebControls.Label lblStateName;
	protected global::System.Web.UI.WebControls.Label lblEnable;
	protected global::System.Web.UI.WebControls.Label lblIsShow;
	protected global::System.Web.UI.WebControls.Label lblOrderNum;
	protected global::System.Web.UI.WebControls.Label lblReasion;
	protected global::System.Web.UI.WebControls.Label lblOperation;


       
    }
}
