//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.Depts {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtDeptID;
		protected global::System.Web.UI.WebControls.TextBox txtDeptName;
		protected global::System.Web.UI.WebControls.TextBox txtUpperDept;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtimgIndex;
		protected global::System.Web.UI.WebControls.TextBox txtSelectimgIndex;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtCustomCode;
		protected global::System.Web.UI.WebControls.TextBox txtDeptType;
		protected global::System.Web.UI.WebControls.TextBox txtLocationX;
		protected global::System.Web.UI.WebControls.TextBox txtLocationY;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
