//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.LostInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtMultiUserID;
		protected global::System.Web.UI.WebControls.TextBox txtCardID;
		protected global::System.Web.UI.WebControls.TextBox txtLostDate;
		protected global::System.Web.UI.WebControls.TextBox txtDownloadDate;
		protected global::System.Web.UI.WebControls.TextBox txtSuccessMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtSuccessDate;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
