//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.AdjustPriceLog {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtExeDate;
		protected global::System.Web.UI.WebControls.TextBox txtMark;
		protected global::System.Web.UI.WebControls.TextBox txtDivid1;
		protected global::System.Web.UI.WebControls.TextBox txtDivid2;
		protected global::System.Web.UI.WebControls.TextBox txtDivid3;
		protected global::System.Web.UI.WebControls.TextBox txtDivid4;
		protected global::System.Web.UI.WebControls.TextBox txtDivid5;
		protected global::System.Web.UI.WebControls.TextBox txtFareID;
		protected global::System.Web.UI.WebControls.TextBox txtFareTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtPrice2;
		protected global::System.Web.UI.WebControls.TextBox txtPrice3;
		protected global::System.Web.UI.WebControls.TextBox txtPrice4;
		protected global::System.Web.UI.WebControls.TextBox txtPrice5;
		protected global::System.Web.UI.WebControls.TextBox txtPrice6;
		protected global::System.Web.UI.WebControls.TextBox txtFareNo;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtPreFareTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtPrePrice;
		protected global::System.Web.UI.WebControls.TextBox txtPrePrice2;
		protected global::System.Web.UI.WebControls.TextBox txtPrePrice3;
		protected global::System.Web.UI.WebControls.TextBox txtPrePrice4;
		protected global::System.Web.UI.WebControls.TextBox txtPrePrice5;
		protected global::System.Web.UI.WebControls.TextBox txtPrePrice6;
		protected global::System.Web.UI.WebControls.TextBox txtPreFareNo;
		protected global::System.Web.UI.WebControls.TextBox txtPreRemark;
		protected global::System.Web.UI.WebControls.TextBox txtSetNo;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeDay;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
