//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.InvoiceHand {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOperID;
	protected global::System.Web.UI.WebControls.Label lblspName;
	protected global::System.Web.UI.WebControls.Label lblspUnit;
	protected global::System.Web.UI.WebControls.Label lblspNum;
	protected global::System.Web.UI.WebControls.Label lblspPrice;
	protected global::System.Web.UI.WebControls.Label lblspMoney;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblInID;


       
    }
}
