//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.FreezeMonthLog {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblFreezeMonth;
	protected global::System.Web.UI.WebControls.Label lblFreezeNumber;
	protected global::System.Web.UI.WebControls.Label lblReadDate;
	protected global::System.Web.UI.WebControls.Label lblInstantNumber;
	protected global::System.Web.UI.WebControls.Label lblPileNumber;
	protected global::System.Web.UI.WebControls.Label lblWatertemp;
	protected global::System.Web.UI.WebControls.Label lblBackWatertemp;
	protected global::System.Web.UI.WebControls.Label lblWorkDate;
	protected global::System.Web.UI.WebControls.Label lblFactDate;
	protected global::System.Web.UI.WebControls.Label lblBatteryState;
	protected global::System.Web.UI.WebControls.Label lblWarning;
	protected global::System.Web.UI.WebControls.Label lblOldFreezeNumber;
	protected global::System.Web.UI.WebControls.Label lblMegabit;
	protected global::System.Web.UI.WebControls.Label lblPriceSetNo;
	protected global::System.Web.UI.WebControls.Label lblCollectorReadDate;
	protected global::System.Web.UI.WebControls.Label lblActiveSharp;
	protected global::System.Web.UI.WebControls.Label lblActivePeak;
	protected global::System.Web.UI.WebControls.Label lblActiveShoulder;
	protected global::System.Web.UI.WebControls.Label lblActiveOffPeak;
	protected global::System.Web.UI.WebControls.Label lblRemnant;
	protected global::System.Web.UI.WebControls.Label lblValveState;


       
    }
}
