//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.GridViewColumnInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblGridViewTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtColumnID;
	protected global::System.Web.UI.WebControls.Label lblDataField;
		protected global::System.Web.UI.WebControls.TextBox txtHeaderText;
		protected global::System.Web.UI.WebControls.TextBox txtDataFormat;
		protected global::System.Web.UI.WebControls.TextBox txtSortExpression;
		protected global::System.Web.UI.WebControls.CheckBox chkIsEdit;
		protected global::System.Web.UI.WebControls.CheckBox chkIsShow;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNum;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
