//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.GridViewColumnInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblGridViewTypeID;
	protected global::System.Web.UI.WebControls.Label lblColumnID;
	protected global::System.Web.UI.WebControls.Label lblDataField;
	protected global::System.Web.UI.WebControls.Label lblHeaderText;
	protected global::System.Web.UI.WebControls.Label lblDataFormat;
	protected global::System.Web.UI.WebControls.Label lblSortExpression;
	protected global::System.Web.UI.WebControls.Label lblIsEdit;
	protected global::System.Web.UI.WebControls.Label lblIsShow;
	protected global::System.Web.UI.WebControls.Label lblOrderNum;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
