//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.DataExportCodeInfo {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtName;
		protected global::System.Web.UI.WebControls.TextBox txtStrSql;
		protected global::System.Web.UI.WebControls.CheckBox chkShowDeptCondition;
		protected global::System.Web.UI.WebControls.TextBox txtInfoCondition;
		protected global::System.Web.UI.WebControls.TextBox txtDateCondition;
		protected global::System.Web.UI.WebControls.TextBox txtExtCondition;
		protected global::System.Web.UI.WebControls.TextBox txtAscString;
		protected global::System.Web.UI.WebControls.TextBox txtGridViewWidth;
		protected global::System.Web.UI.WebControls.TextBox txtExportType;
		protected global::System.Web.UI.WebControls.CheckBox chkShowHeader;
		protected global::System.Web.UI.WebControls.TextBox txtSplitChar;
		protected global::System.Web.UI.WebControls.TextBox txtCreateDbfSql;
		protected global::System.Web.UI.WebControls.TextBox txtDbfFileName;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtEndDateCondition;
		protected global::System.Web.UI.WebControls.TextBox txtShowOtherHeader;
		protected global::System.Web.UI.WebControls.TextBox txtExportCols;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
