//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.DataExportCodeInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblStrSql;
	protected global::System.Web.UI.WebControls.Label lblShowDeptCondition;
	protected global::System.Web.UI.WebControls.Label lblInfoCondition;
	protected global::System.Web.UI.WebControls.Label lblDateCondition;
	protected global::System.Web.UI.WebControls.Label lblExtCondition;
	protected global::System.Web.UI.WebControls.Label lblAscString;
	protected global::System.Web.UI.WebControls.Label lblGridViewWidth;
	protected global::System.Web.UI.WebControls.Label lblExportType;
	protected global::System.Web.UI.WebControls.Label lblShowHeader;
	protected global::System.Web.UI.WebControls.Label lblSplitChar;
	protected global::System.Web.UI.WebControls.Label lblCreateDbfSql;
	protected global::System.Web.UI.WebControls.Label lblDbfFileName;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblEndDateCondition;
	protected global::System.Web.UI.WebControls.Label lblShowOtherHeader;
	protected global::System.Web.UI.WebControls.Label lblExportCols;


       
    }
}
