//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PaymentList {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblOperID;
		protected global::System.Web.UI.WebControls.TextBox txtUsersID;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceNum;
		protected global::System.Web.UI.WebControls.TextBox txtLastbalance;
		protected global::System.Web.UI.WebControls.TextBox txtThisMoney;
		protected global::System.Web.UI.WebControls.TextBox txtFactMoney;
		protected global::System.Web.UI.WebControls.TextBox txtThisBalance;
		protected global::System.Web.UI.WebControls.TextBox txtPayDate;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtPayMode;
		protected global::System.Web.UI.WebControls.TextBox txtFlag;
		protected global::System.Web.UI.WebControls.TextBox txtSiteID;
		protected global::System.Web.UI.WebControls.TextBox txtOperInt;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceID;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceType;
		protected global::System.Web.UI.WebControls.TextBox txtPayType;
		protected global::System.Web.UI.WebControls.TextBox txtPayWay;
		protected global::System.Web.UI.WebControls.TextBox txtTransactionId;
		protected global::System.Web.UI.WebControls.TextBox txtOutTradeNo;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
