//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PaymentList {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOperID;
	protected global::System.Web.UI.WebControls.Label lblUsersID;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblInvoiceNum;
	protected global::System.Web.UI.WebControls.Label lblLastbalance;
	protected global::System.Web.UI.WebControls.Label lblThisMoney;
	protected global::System.Web.UI.WebControls.Label lblFactMoney;
	protected global::System.Web.UI.WebControls.Label lblThisBalance;
	protected global::System.Web.UI.WebControls.Label lblPayDate;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblPayMode;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblOperInt;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblInvoiceID;
	protected global::System.Web.UI.WebControls.Label lblInvoiceType;
	protected global::System.Web.UI.WebControls.Label lblPayType;
	protected global::System.Web.UI.WebControls.Label lblPayWay;
	protected global::System.Web.UI.WebControls.Label lblTransactionId;
	protected global::System.Web.UI.WebControls.Label lblOutTradeNo;


       
    }
}
