//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterImageData {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblReadTime;
	protected global::System.Web.UI.WebControls.Label lblVoltage;
	protected global::System.Web.UI.WebControls.Label lblValveState;
	protected global::System.Web.UI.WebControls.Label lblLowVoltage;
	protected global::System.Web.UI.WebControls.Label lblMagneticDisturb;
	protected global::System.Web.UI.WebControls.Label lblImageQuality;
	protected global::System.Web.UI.WebControls.Label lblEnableUpload;
	protected global::System.Web.UI.WebControls.Label lblMeterImage;
	protected global::System.Web.UI.WebControls.Label lblInsertDate;
	protected global::System.Web.UI.WebControls.Label lblFreezeNumber;
	protected global::System.Web.UI.WebControls.Label lblLeftMeterImage;
	protected global::System.Web.UI.WebControls.Label lblRightMeterImage;


       
    }
}
