//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ManageFare {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblManageFareID;
	protected global::System.Web.UI.WebControls.Label lblManageFareName;
	protected global::System.Web.UI.WebControls.Label lblManageFarePrice;
	protected global::System.Web.UI.WebControls.Label lblManageFareTypeID;
	protected global::System.Web.UI.WebControls.Label lblReMark;
	protected global::System.Web.UI.WebControls.Label lblSystemNum;


       
    }
}
