//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.UserFeedBack {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtContactWay;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtContent;
		protected global::System.Web.UI.WebControls.TextBox txtPublishDate;
		protected global::System.Web.UI.WebControls.TextBox txtReplyMan;
		protected global::System.Web.UI.WebControls.TextBox txtReplyContent;
		protected global::System.Web.UI.WebControls.TextBox txtReplyDate;
		protected global::System.Web.UI.WebControls.TextBox txtFlag;
		protected global::System.Web.UI.WebControls.TextBox txtTypeId;
		protected global::System.Web.UI.WebControls.TextBox txtContact;
		protected global::System.Web.UI.WebControls.TextBox txtReplyFlag;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
