//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.UserFeedBack {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblUserCode;
	protected global::System.Web.UI.WebControls.Label lblContactWay;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblContent;
	protected global::System.Web.UI.WebControls.Label lblPublishDate;
	protected global::System.Web.UI.WebControls.Label lblReplyMan;
	protected global::System.Web.UI.WebControls.Label lblReplyContent;
	protected global::System.Web.UI.WebControls.Label lblReplyDate;
	protected global::System.Web.UI.WebControls.Label lblFlag;
	protected global::System.Web.UI.WebControls.Label lblTypeId;
	protected global::System.Web.UI.WebControls.Label lblContact;
	protected global::System.Web.UI.WebControls.Label lblReplyFlag;


       
    }
}
