//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ChangeMeterRegist {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtUsersID;
		protected global::System.Web.UI.WebControls.TextBox txtUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtOldNumber;
		protected global::System.Web.UI.WebControls.TextBox txtNewMeterAddr;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtStatus;
		protected global::System.Web.UI.WebControls.TextBox txtImagePath;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorCode;
		protected global::System.Web.UI.WebControls.TextBox txtNewNumber;
		protected global::System.Web.UI.WebControls.TextBox txtNewMeterId;
		protected global::System.Web.UI.WebControls.TextBox txtInsertDate;
		protected global::System.Web.UI.WebControls.TextBox txtChangeMeterDate;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
