//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ChangeMeterRegist {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblUsersID;
	protected global::System.Web.UI.WebControls.Label lblUserCode;
	protected global::System.Web.UI.WebControls.Label lblOldNumber;
	protected global::System.Web.UI.WebControls.Label lblNewMeterAddr;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblStatus;
	protected global::System.Web.UI.WebControls.Label lblImagePath;
	protected global::System.Web.UI.WebControls.Label lblOperatorCode;
	protected global::System.Web.UI.WebControls.Label lblNewNumber;
	protected global::System.Web.UI.WebControls.Label lblNewMeterId;
	protected global::System.Web.UI.WebControls.Label lblInsertDate;
	protected global::System.Web.UI.WebControls.Label lblChangeMeterDate;
	protected global::System.Web.UI.WebControls.Label lblMeterID;


       
    }
}
