//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PreOperation {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblOperID;
		protected global::System.Web.UI.WebControls.TextBox txtCardID;
		protected global::System.Web.UI.WebControls.TextBox txtCardSector;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeID;
		protected global::System.Web.UI.WebControls.TextBox txtPriceTypeName;
		protected global::System.Web.UI.WebControls.TextBox txtPrice;
		protected global::System.Web.UI.WebControls.TextBox txtOperMoney;
		protected global::System.Web.UI.WebControls.TextBox txtOperInt;
		protected global::System.Web.UI.WebControls.TextBox txtOperZS;
		protected global::System.Web.UI.WebControls.TextBox txtFactMoney;
		protected global::System.Web.UI.WebControls.TextBox txtLastBalance;
		protected global::System.Web.UI.WebControls.TextBox txtCurrentBalance;
		protected global::System.Web.UI.WebControls.TextBox txtTotalMoney;
		protected global::System.Web.UI.WebControls.TextBox txtTotalInt;
		protected global::System.Web.UI.WebControls.TextBox txtTotalBase;
		protected global::System.Web.UI.WebControls.TextBox txtOperType;
		protected global::System.Web.UI.WebControls.TextBox txtPayType;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceCode;
	protected global::System.Web.UI.WebControls.Label lblOperDate;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtOperatorID;
		protected global::System.Web.UI.WebControls.TextBox txtSiteID;
		protected global::System.Web.UI.WebControls.TextBox txtFactoryNum;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtRedOperId;
		protected global::System.Web.UI.WebControls.TextBox txtOperNum;
		protected global::System.Web.UI.WebControls.TextBox txtPrice2;
		protected global::System.Web.UI.WebControls.TextBox txtPrice3;
		protected global::System.Web.UI.WebControls.TextBox txtDivid1;
		protected global::System.Web.UI.WebControls.TextBox txtDivid2;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber1;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber2;
		protected global::System.Web.UI.WebControls.TextBox txtUseNumber3;
		protected global::System.Web.UI.WebControls.TextBox txtCurTotalBuyNumber;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceID;
		protected global::System.Web.UI.WebControls.TextBox txtInvoiceType;
		protected global::System.Web.UI.WebControls.TextBox txtWriteCardFlag;
		protected global::System.Web.UI.WebControls.TextBox txtTransactionId;
		protected global::System.Web.UI.WebControls.TextBox txtPayWay;
		protected global::System.Web.UI.WebControls.TextBox txtOutTradeNo;
		protected global::System.Web.UI.WebControls.TextBox txtDepositDate;
		protected global::System.Web.UI.WebControls.TextBox txtDiscountsNum;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
