//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.PreOperation {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOperID;
	protected global::System.Web.UI.WebControls.Label lblCardID;
	protected global::System.Web.UI.WebControls.Label lblCardSector;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeID;
	protected global::System.Web.UI.WebControls.Label lblPriceTypeName;
	protected global::System.Web.UI.WebControls.Label lblPrice;
	protected global::System.Web.UI.WebControls.Label lblOperMoney;
	protected global::System.Web.UI.WebControls.Label lblOperInt;
	protected global::System.Web.UI.WebControls.Label lblOperZS;
	protected global::System.Web.UI.WebControls.Label lblFactMoney;
	protected global::System.Web.UI.WebControls.Label lblLastBalance;
	protected global::System.Web.UI.WebControls.Label lblCurrentBalance;
	protected global::System.Web.UI.WebControls.Label lblTotalMoney;
	protected global::System.Web.UI.WebControls.Label lblTotalInt;
	protected global::System.Web.UI.WebControls.Label lblTotalBase;
	protected global::System.Web.UI.WebControls.Label lblOperType;
	protected global::System.Web.UI.WebControls.Label lblPayType;
	protected global::System.Web.UI.WebControls.Label lblInvoiceCode;
	protected global::System.Web.UI.WebControls.Label lblOperDate;
	protected global::System.Web.UI.WebControls.Label lblMeterID;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblFactoryNum;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblRedOperId;
	protected global::System.Web.UI.WebControls.Label lblOperNum;
	protected global::System.Web.UI.WebControls.Label lblPrice2;
	protected global::System.Web.UI.WebControls.Label lblPrice3;
	protected global::System.Web.UI.WebControls.Label lblDivid1;
	protected global::System.Web.UI.WebControls.Label lblDivid2;
	protected global::System.Web.UI.WebControls.Label lblUseNumber1;
	protected global::System.Web.UI.WebControls.Label lblUseNumber2;
	protected global::System.Web.UI.WebControls.Label lblUseNumber3;
	protected global::System.Web.UI.WebControls.Label lblCurTotalBuyNumber;
	protected global::System.Web.UI.WebControls.Label lblInvoiceID;
	protected global::System.Web.UI.WebControls.Label lblInvoiceType;
	protected global::System.Web.UI.WebControls.Label lblWriteCardFlag;
	protected global::System.Web.UI.WebControls.Label lblTransactionId;
	protected global::System.Web.UI.WebControls.Label lblPayWay;
	protected global::System.Web.UI.WebControls.Label lblOutTradeNo;
	protected global::System.Web.UI.WebControls.Label lblDepositDate;
	protected global::System.Web.UI.WebControls.Label lblDiscountsNum;


       
    }
}
