//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.BlanceAccount {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtBlanceDate;
		protected global::System.Web.UI.WebControls.TextBox txtFailUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtFail;
		protected global::System.Web.UI.WebControls.TextBox txtAllCount;
		protected global::System.Web.UI.WebControls.TextBox txtAllMoney;
		protected global::System.Web.UI.WebControls.TextBox txtRefundMoney;
		protected global::System.Web.UI.WebControls.TextBox txtBlanceTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
