//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.MeterImageDataLog {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtMeterID;
		protected global::System.Web.UI.WebControls.TextBox txtReadTime;
		protected global::System.Web.UI.WebControls.TextBox txtVoltage;
		protected global::System.Web.UI.WebControls.TextBox txtValveState;
		protected global::System.Web.UI.WebControls.CheckBox chkLowVoltage;
		protected global::System.Web.UI.WebControls.CheckBox chkMagneticDisturb;
		protected global::System.Web.UI.WebControls.TextBox txtImageQuality;
		protected global::System.Web.UI.WebControls.CheckBox chkEnableUpload;
		protected global::System.Web.UI.WebControls.TextBox txtMeterImage;
		protected global::System.Web.UI.WebControls.TextBox txtInsertDate;
		protected global::System.Web.UI.WebControls.TextBox txtFreezeNumber;
		protected global::System.Web.UI.WebControls.TextBox txtLeftMeterImage;
		protected global::System.Web.UI.WebControls.TextBox txtRightMeterImage;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
