//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.InstallFee {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblInstallID;
	protected global::System.Web.UI.WebControls.Label lblUserNum;
	protected global::System.Web.UI.WebControls.Label lblSingleFee;
	protected global::System.Web.UI.WebControls.Label lblSumFee;
	protected global::System.Web.UI.WebControls.Label lblOperDate;
	protected global::System.Web.UI.WebControls.Label lblOperatorID;
	protected global::System.Web.UI.WebControls.Label lblSiteID;
	protected global::System.Web.UI.WebControls.Label lblMark;
	protected global::System.Web.UI.WebControls.Label lblInstallMark;


       
    }
}
