//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ClientSoftInfo {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtDanWeiName;
		protected global::System.Web.UI.WebControls.TextBox txtJiQiMa;
		protected global::System.Web.UI.WebControls.TextBox txtRenZhengMa;
		protected global::System.Web.UI.WebControls.TextBox txtSoftName;
		protected global::System.Web.UI.WebControls.TextBox txtSoftHao;
		protected global::System.Web.UI.WebControls.TextBox txtUsePassword;
		protected global::System.Web.UI.WebControls.TextBox txtJieTiCalDate;
		protected global::System.Web.UI.WebControls.TextBox txtSqlVersion;
		protected global::System.Web.UI.WebControls.TextBox txtMeterTypes;
		protected global::System.Web.UI.WebControls.TextBox txtCardTypes;
		protected global::System.Web.UI.WebControls.TextBox txtPayTypes;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
