//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.ClientSoftInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblId;
	protected global::System.Web.UI.WebControls.Label lblDanWeiName;
	protected global::System.Web.UI.WebControls.Label lblJiQiMa;
	protected global::System.Web.UI.WebControls.Label lblRenZhengMa;
	protected global::System.Web.UI.WebControls.Label lblSoftName;
	protected global::System.Web.UI.WebControls.Label lblSoftHao;
	protected global::System.Web.UI.WebControls.Label lblUsePassword;
	protected global::System.Web.UI.WebControls.Label lblJieTiCalDate;
	protected global::System.Web.UI.WebControls.Label lblSqlVersion;
	protected global::System.Web.UI.WebControls.Label lblMeterTypes;
	protected global::System.Web.UI.WebControls.Label lblCardTypes;
	protected global::System.Web.UI.WebControls.Label lblPayTypes;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;


       
    }
}
