//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.BookInfo {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBookID;
	protected global::System.Web.UI.WebControls.Label lblDeptIDs;
	protected global::System.Web.UI.WebControls.Label lblBookName;
	protected global::System.Web.UI.WebControls.Label lblWorkerID;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblBookCode;
	protected global::System.Web.UI.WebControls.Label lblRoutes;
	protected global::System.Web.UI.WebControls.Label lblReadDay;
	protected global::System.Web.UI.WebControls.Label lblReadType;
	protected global::System.Web.UI.WebControls.Label lblUserNum;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblAutoReadBeginDate;
	protected global::System.Web.UI.WebControls.Label lblAutoReadEndDate;


       
    }
}
