//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.users {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUsersID;
		protected global::System.Web.UI.WebControls.TextBox txtUserCode;
		protected global::System.Web.UI.WebControls.TextBox txtUserName;
		protected global::System.Web.UI.WebControls.TextBox txtDoorplate;
		protected global::System.Web.UI.WebControls.TextBox txtPaperType;
		protected global::System.Web.UI.WebControls.TextBox txtPaperNo;
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtPhone;
		protected global::System.Web.UI.WebControls.TextBox txtTel;
		protected global::System.Web.UI.WebControls.TextBox txtAcreage;
		protected global::System.Web.UI.WebControls.TextBox txtChargeAcreage;
		protected global::System.Web.UI.WebControls.TextBox txtReserve;
		protected global::System.Web.UI.WebControls.TextBox txtSex;
		protected global::System.Web.UI.WebControls.TextBox txtPopulace;
		protected global::System.Web.UI.WebControls.TextBox txtRemark;
		protected global::System.Web.UI.WebControls.TextBox txtMark;
		protected global::System.Web.UI.WebControls.TextBox txtDeptID;
		protected global::System.Web.UI.WebControls.TextBox txtUserFloor;
		protected global::System.Web.UI.WebControls.TextBox txtHouseDir;
		protected global::System.Web.UI.WebControls.TextBox txtUserType;
		protected global::System.Web.UI.WebControls.TextBox txtClientId;
		protected global::System.Web.UI.WebControls.TextBox txtRemnant;
		protected global::System.Web.UI.WebControls.TextBox txtRemnant2;
		protected global::System.Web.UI.WebControls.TextBox txtRemnant3;
		protected global::System.Web.UI.WebControls.TextBox txtUpdateTime;
		protected global::System.Web.UI.WebControls.TextBox txtRegistPhone;
		protected global::System.Web.UI.WebControls.TextBox txtEInvoiceType;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
