//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Web.WebDemo.users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUsersID;
	protected global::System.Web.UI.WebControls.Label lblUserCode;
	protected global::System.Web.UI.WebControls.Label lblUserName;
	protected global::System.Web.UI.WebControls.Label lblDoorplate;
	protected global::System.Web.UI.WebControls.Label lblPaperType;
	protected global::System.Web.UI.WebControls.Label lblPaperNo;
	protected global::System.Web.UI.WebControls.Label lblAddress;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblTel;
	protected global::System.Web.UI.WebControls.Label lblAcreage;
	protected global::System.Web.UI.WebControls.Label lblChargeAcreage;
	protected global::System.Web.UI.WebControls.Label lblReserve;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblPopulace;
	protected global::System.Web.UI.WebControls.Label lblRemark;
	protected global::System.Web.UI.WebControls.Label lblMark;
	protected global::System.Web.UI.WebControls.Label lblDeptID;
	protected global::System.Web.UI.WebControls.Label lblUserFloor;
	protected global::System.Web.UI.WebControls.Label lblHouseDir;
	protected global::System.Web.UI.WebControls.Label lblUserType;
	protected global::System.Web.UI.WebControls.Label lblClientId;
	protected global::System.Web.UI.WebControls.Label lblRemnant;
	protected global::System.Web.UI.WebControls.Label lblRemnant2;
	protected global::System.Web.UI.WebControls.Label lblRemnant3;
	protected global::System.Web.UI.WebControls.Label lblUpdateTime;
	protected global::System.Web.UI.WebControls.Label lblRegistPhone;
	protected global::System.Web.UI.WebControls.Label lblEInvoiceType;


       
    }
}
